// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaF_UznOgRBLJZ0tNcABUr-PrDFMyc9Xk',
    appId: '1:648958053897:web:99a585daf09aad6d36b2d8',
    messagingSenderId: '648958053897',
    projectId: 'kwikpro-app',
    authDomain: 'kwikpro-app.firebaseapp.com',
    storageBucket: 'kwikpro-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrnWTKKc7dUK3L-xLVi2dwFuCN8cHCYKk',
    appId: '1:648958053897:android:287e9ce50154ac8e36b2d8',
    messagingSenderId: '648958053897',
    projectId: 'kwikpro-app',
    storageBucket: 'kwikpro-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaF_UznOgRBLJZ0tNcABUr-PrDFMyc9Xk',
    appId: '1:648958053897:web:5ddecb88f251d4aa36b2d8',
    messagingSenderId: '648958053897',
    projectId: 'kwikpro-app',
    authDomain: 'kwikpro-app.firebaseapp.com',
    storageBucket: 'kwikpro-app.firebasestorage.app',
  );

}